### PR TITLE
NEX-48: Search improvements

### PR DESCRIPTION
**Pull request by joshua-scott**
Continuing from https://github.com/wunderio/next4drupal-project/pull/84, this PR further improves the search feature.

*Changes proposed in this PR:*
- do not open search results in a new tab
- fix search pagination and use the design from [the component library](https://www.figma.com/file/i0RIoStoPOZfcqS80DLbkD/The-Component-Library?type=design&node-id=895%3A6574&t=JVWWhJH84lxB5KMA-1)
- use checkbox to style the tags to the left of search results
- small fixes to button styles (e35608b1d0a1e776d8cf33e8868461daa45550dc,  8e474f38c80321ffff80562ebbe1d15ee228cd7d)

CleanShot 2023-05-08 at 16 57 38
CleanShot 2023-05-08 at 17 03 34

*How to test:*
- Go to the environment using the link below (or checkout locally, whichever) and test the /search page works nicely, especially those features mentioned above

*Link to feature environment:*
https://feature-nex-48-search-improvemef6.next4drupal-project.dev.wdr.io

### CODE REVIEW

**Comment by vermario** [comment]
@joshua-scott  the search bar component looks a bit off on Firefox: 

image

(it looks ok on Chrome)

**Comment by vermario** [comment]
@joshua-scott I have figured out what does not work correctly with opening results in the same page: 

1. go to search, do not input any search query, press enter, you will see all results
2. click on one result, you go to that result's  page
3. go back with the browser, you will get the search page with no results, because because the url does not have a search query

maybe we can still live with this anyway?

**Comment by vermario** [comment]
@joshua-scott I found this page about making elastic ui and next.js play along nicely: https://docs.elastic.co/search-ui/guides/nextjs-integration#integrating-search-ui-with-nextjs-router

**Review by Zionknight-crypto — APPROVED** [review]
Stunning work mate!

**Review by Zionknight-crypto — APPROVED** [review]
Stunning work mate!

**Pull request merged**
